# Generated by Django 4.2.5 on 2023-09-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='show_contact',
            new_name='show',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
